#!/bin/bash
#
# audit_config.sh - Comprehensive Auditd Configuration Script
#
#
# Configures the Linux audit subsystem with comprehensive security
# monitoring rules. Rules are organized by category and follow
# CIS Benchmark and STIG recommendations.
#
# Usage: sudo ./audit_config.sh [--install|--verify|--remove]
#
# Modes:
#   --install   Install audit rules (default)
#   --verify    Verify rules are loaded and working
#   --remove    Remove installed rules
#   --test      Install rules and generate test events
#

set -euo pipefail

RULES_DIR="/etc/audit/rules.d"
RULES_FILE="${RULES_DIR}/99-security-monitoring.rules"
LOG_FILE="/var/log/audit_config.log"
MODE="install"

# ── Parse arguments ─────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --install)  MODE="install"; shift ;;
        --verify)   MODE="verify"; shift ;;
        --remove)   MODE="remove"; shift ;;
        --test)     MODE="test"; shift ;;
        --help|-h)
            echo "Usage: $0 [--install|--verify|--remove|--test]"
            echo ""
            echo "Installs comprehensive auditd security monitoring rules."
            echo ""
            echo "Must be run as root."
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [[ $(id -u) -ne 0 ]]; then
    echo "ERROR: Must be run as root."
    exit 1
fi

# ── Check prerequisites ────────────────────────────────────────

check_prerequisites() {
    if ! command -v auditctl &> /dev/null; then
        echo "ERROR: auditctl not found. Install auditd:"
        echo "  Debian/Ubuntu: apt install auditd audispd-plugins"
        echo "  RHEL/Fedora:   dnf install audit"
        exit 1
    fi

    if ! systemctl is-active --quiet auditd 2>/dev/null; then
        echo "WARNING: auditd is not running. Starting it..."
        systemctl start auditd || true
    fi
}

# ── Install audit rules ────────────────────────────────────────

install_rules() {
    check_prerequisites

    echo "============================================================"
    echo "  Installing Comprehensive Audit Rules"
    echo "  $(date)"
    echo "============================================================"
    echo ""

    mkdir -p "$RULES_DIR"

    cat > "$RULES_FILE" << 'AUDITRULES'
## ============================================================
## Comprehensive Security Audit Rules
## Auto-generated by audit_config.sh
## Forensics and Hardening
## ============================================================

## ── Cleanup ──
## Delete all existing rules on load
-D

## ── Buffer Configuration ──
## Increase audit buffer for busy systems (default: 64)
-b 8192

## ── Failure Mode ──
## 0=silent, 1=printk, 2=panic
## Use 1 for logging; use 2 for high-security environments
-f 1

## ============================================================
## SECTION 1: IDENTITY AND AUTHENTICATION
## ============================================================

## User/group database modifications
-w /etc/passwd -p wa -k identity_change
-w /etc/shadow -p wa -k identity_change
-w /etc/group -p wa -k identity_change
-w /etc/gshadow -p wa -k identity_change
-w /etc/security/opasswd -p wa -k identity_change

## PAM configuration changes
-w /etc/pam.d/ -p wa -k pam_config
-w /etc/security/ -p wa -k security_config

## Login configuration
-w /etc/login.defs -p wa -k login_config
-w /etc/securetty -p wa -k login_config

## SSH configuration
-w /etc/ssh/sshd_config -p wa -k ssh_config
-w /etc/ssh/sshd_config.d/ -p wa -k ssh_config

## NSS configuration
-w /etc/nsswitch.conf -p wa -k nss_config

## ============================================================
## SECTION 2: PRIVILEGE ESCALATION
## ============================================================

## sudo and su usage
-w /usr/bin/sudo -p x -k privilege_escalation
-w /usr/bin/su -p x -k privilege_escalation
-w /etc/sudoers -p wa -k sudoers_change
-w /etc/sudoers.d/ -p wa -k sudoers_change

## setuid/setgid/setresuid/setresgid syscalls
-a always,exit -F arch=b64 -S setuid,setresuid,setreuid -F a0!=0 -k privilege_change
-a always,exit -F arch=b64 -S setgid,setresgid,setregid -F a0!=0 -k privilege_change
-a always,exit -F arch=b32 -S setuid,setresuid,setreuid -F a0!=0 -k privilege_change
-a always,exit -F arch=b32 -S setgid,setresgid,setregid -F a0!=0 -k privilege_change

## Changes to file permissions/ownership
-a always,exit -F arch=b64 -S chmod,fchmod,fchmodat -k permission_change
-a always,exit -F arch=b64 -S chown,fchown,fchownat,lchown -k ownership_change
-a always,exit -F arch=b32 -S chmod,fchmod,fchmodat -k permission_change
-a always,exit -F arch=b32 -S chown,fchown,fchownat,lchown -k ownership_change

## ============================================================
## SECTION 3: KERNEL AND MODULE OPERATIONS
## ============================================================

## Kernel module loading and unloading
-a always,exit -F arch=b64 -S init_module,finit_module -k module_load
-a always,exit -F arch=b64 -S delete_module -k module_unload
-a always,exit -F arch=b32 -S init_module,finit_module -k module_load
-a always,exit -F arch=b32 -S delete_module -k module_unload

## Module management tools
-w /sbin/insmod -p x -k module_tools
-w /sbin/modprobe -p x -k module_tools
-w /sbin/rmmod -p x -k module_tools

## Kexec (kernel replacement)
-a always,exit -F arch=b64 -S kexec_load,kexec_file_load -k kexec
-a always,exit -F arch=b32 -S kexec_load -k kexec

## BPF operations
-a always,exit -F arch=b64 -S bpf -k bpf_activity
-a always,exit -F arch=b32 -S bpf -k bpf_activity

## ptrace (process injection/debugging)
-a always,exit -F arch=b64 -S ptrace -k ptrace_activity
-a always,exit -F arch=b32 -S ptrace -k ptrace_activity

## Sysctl modifications
-w /etc/sysctl.conf -p wa -k sysctl_change
-w /etc/sysctl.d/ -p wa -k sysctl_change

## ============================================================
## SECTION 4: FILE SYSTEM INTEGRITY
## ============================================================

## Critical binary directories
-w /bin/ -p wa -k binary_change
-w /sbin/ -p wa -k binary_change
-w /usr/bin/ -p wa -k binary_change
-w /usr/sbin/ -p wa -k binary_change

## Library directories
-w /lib/ -p wa -k library_change
-w /lib64/ -p wa -k library_change
-w /usr/lib/ -p wa -k library_change

## Boot files and bootloader
-w /boot/ -p wa -k boot_change
-w /etc/grub.d/ -p wa -k grub_change
-w /etc/default/grub -p wa -k grub_change

## Dynamic linker configuration (LD_PRELOAD attacks)
-w /etc/ld.so.conf -p wa -k linker_config
-w /etc/ld.so.conf.d/ -p wa -k linker_config
-w /etc/ld.so.preload -p wa -k ld_preload

## ============================================================
## SECTION 5: NETWORK CONFIGURATION
## ============================================================

## Network configuration files
-w /etc/hosts -p wa -k network_config
-w /etc/hostname -p wa -k network_config
-w /etc/resolv.conf -p wa -k network_config
-w /etc/NetworkManager/ -p wa -k network_config
-w /etc/netplan/ -p wa -k network_config

## Firewall rules
-w /etc/nftables.conf -p wa -k firewall_change
-w /etc/iptables/ -p wa -k firewall_change

## ============================================================
## SECTION 6: SCHEDULED TASKS
## ============================================================

## Cron configuration
-w /etc/crontab -p wa -k cron_change
-w /etc/cron.d/ -p wa -k cron_change
-w /etc/cron.daily/ -p wa -k cron_change
-w /etc/cron.hourly/ -p wa -k cron_change
-w /etc/cron.weekly/ -p wa -k cron_change
-w /etc/cron.monthly/ -p wa -k cron_change
-w /var/spool/cron/ -p wa -k cron_change
-w /etc/anacrontab -p wa -k cron_change

## Systemd timer units
-w /etc/systemd/system/ -p wa -k systemd_change
-w /usr/lib/systemd/system/ -p wa -k systemd_change

## At jobs
-w /var/spool/at/ -p wa -k at_change

## ============================================================
## SECTION 7: SUSPICIOUS ACTIVITY
## ============================================================

## Unauthorized access attempts
-a always,exit -F arch=b64 -S open,openat -F exit=-EACCES -k access_denied
-a always,exit -F arch=b64 -S open,openat -F exit=-EPERM -k access_denied
-a always,exit -F arch=b32 -S open,openat -F exit=-EACCES -k access_denied
-a always,exit -F arch=b32 -S open,openat -F exit=-EPERM -k access_denied

## Process execution tracking
-a always,exit -F arch=b64 -S execve -k process_exec
-a always,exit -F arch=b32 -S execve -k process_exec

## File deletion by users
-a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k file_deletion
-a always,exit -F arch=b32 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k file_deletion

## Mounting operations
-a always,exit -F arch=b64 -S mount -k mount_activity
-a always,exit -F arch=b32 -S mount -k mount_activity

## ============================================================
## SECTION 8: AUDIT CONFIGURATION PROTECTION
## ============================================================

## Monitor changes to audit configuration
-w /etc/audit/ -p wa -k audit_config
-w /etc/audisp/ -p wa -k audit_config
-w /var/log/audit/ -p wa -k audit_logs

## ============================================================
## LOCK DOWN AUDIT CONFIGURATION
## Uncomment the following line to make audit rules immutable
## (requires reboot to change). Only enable in production.
## ============================================================
## -e 2

AUDITRULES

    echo "Rules written to: $RULES_FILE"
    echo ""

    # Load the rules
    echo "Loading audit rules..."
    if augenrules --load 2>&1; then
        echo "Rules loaded successfully."
    else
        echo "WARNING: augenrules failed. Trying auditctl directly..."
        auditctl -R "$RULES_FILE" 2>&1 || true
    fi

    # Show summary
    local rule_count
    rule_count=$(auditctl -l 2>/dev/null | wc -l)
    echo ""
    echo "Active audit rules: $rule_count"
    echo ""

    # Log the action
    echo "$(date): Audit rules installed ($rule_count rules)" >> "$LOG_FILE"

    echo "============================================================"
    echo "  Audit rules installed successfully."
    echo ""
    echo "  To verify: $0 --verify"
    echo "  To test:   $0 --test"
    echo ""
    echo "  IMPORTANT: To make rules immutable (prevent tampering),"
    echo "  uncomment '-e 2' at the end of $RULES_FILE"
    echo "  and reload. This requires a reboot to change."
    echo "============================================================"
}

# ── Verify audit rules ─────────────────────────────────────────

verify_rules() {
    check_prerequisites

    echo "============================================================"
    echo "  Audit Rules Verification"
    echo "  $(date)"
    echo "============================================================"
    echo ""

    # Check auditd status
    echo "--- auditd Status ---"
    if systemctl is-active --quiet auditd 2>/dev/null; then
        echo "  auditd: RUNNING"
    else
        echo "  auditd: NOT RUNNING (critical!)"
    fi
    echo ""

    # Check audit status
    echo "--- Audit Subsystem Status ---"
    auditctl -s
    echo ""

    # Count rules by category
    echo "--- Rules by Category ---"
    local total_rules
    total_rules=$(auditctl -l 2>/dev/null | wc -l)
    echo "  Total rules loaded: $total_rules"

    declare -A categories
    while IFS= read -r line; do
        if [[ "$line" == *"-k "* ]]; then
            key=$(echo "$line" | grep -oP '(?<=-k )\S+')
            categories["$key"]=$(( ${categories["$key"]:-0} + 1 ))
        fi
    done < <(auditctl -l 2>/dev/null)

    for cat in $(echo "${!categories[@]}" | tr ' ' '\n' | sort); do
        printf "  %-30s %d rules\n" "$cat" "${categories[$cat]}"
    done
    echo ""

    # Check for critical rules
    echo "--- Critical Rule Verification ---"
    local critical_keys=(
        "module_load" "module_unload" "bpf_activity" "ptrace_activity"
        "privilege_escalation" "identity_change" "binary_change"
        "boot_change" "ld_preload" "process_exec"
    )

    local missing=0
    for key in "${critical_keys[@]}"; do
        if auditctl -l 2>/dev/null | grep -q "key=$key"; then
            printf "  [OK]   %-30s PRESENT\n" "$key"
        else
            printf "  [FAIL] %-30s MISSING\n" "$key"
            missing=$((missing + 1))
        fi
    done
    echo ""

    # Check log file
    echo "--- Audit Log Status ---"
    if [[ -f /var/log/audit/audit.log ]]; then
        local log_size
        log_size=$(du -sh /var/log/audit/audit.log | awk '{print $1}')
        local log_events
        log_events=$(wc -l < /var/log/audit/audit.log)
        echo "  Log file: /var/log/audit/audit.log"
        echo "  Size: $log_size"
        echo "  Events: $log_events"
        echo "  Last event: $(tail -1 /var/log/audit/audit.log | head -c 80)..."
    else
        echo "  Log file not found!"
    fi
    echo ""

    echo "============================================================"
    if [[ $missing -eq 0 ]]; then
        echo "  RESULT: All critical audit rules are in place."
    else
        echo "  RESULT: $missing critical rules are MISSING."
        echo "  Run '$0 --install' to install rules."
    fi
    echo "============================================================"
}

# ── Remove audit rules ─────────────────────────────────────────

remove_rules() {
    echo "Removing audit rules..."

    if [[ -f "$RULES_FILE" ]]; then
        rm -f "$RULES_FILE"
        echo "Removed: $RULES_FILE"
    fi

    # Reload to remove custom rules
    auditctl -D 2>/dev/null || true
    augenrules --load 2>/dev/null || true

    echo "Audit rules removed."
    echo "$(date): Audit rules removed" >> "$LOG_FILE"
}

# ── Test audit rules ───────────────────────────────────────────

test_rules() {
    install_rules

    echo ""
    echo "============================================================"
    echo "  Testing Audit Rules"
    echo "============================================================"
    echo ""

    echo "Generating test events..."
    echo ""

    # Test identity change detection
    echo "Test 1: Touch /etc/passwd (identity_change)"
    touch /etc/passwd
    sleep 1
    local result
    result=$(ausearch -k identity_change -ts recent --raw 2>/dev/null | wc -l)
    echo "  Events captured: $result"

    # Test binary change detection
    echo "Test 2: Touch /usr/bin/test_audit_binary (binary_change)"
    touch /usr/bin/test_audit_binary 2>/dev/null || true
    sleep 1
    result=$(ausearch -k binary_change -ts recent --raw 2>/dev/null | wc -l)
    echo "  Events captured: $result"
    rm -f /usr/bin/test_audit_binary 2>/dev/null || true

    # Test cron change detection
    echo "Test 3: Touch /etc/crontab (cron_change)"
    touch /etc/crontab
    sleep 1
    result=$(ausearch -k cron_change -ts recent --raw 2>/dev/null | wc -l)
    echo "  Events captured: $result"

    echo ""
    echo "============================================================"
    echo "  Test complete. Review events with:"
    echo "    ausearch -k <key_name> -ts recent"
    echo "    aureport --summary"
    echo "============================================================"
}

# ── Main ────────────────────────────────────────────────────────

case "$MODE" in
    install) install_rules ;;
    verify)  verify_rules ;;
    remove)  remove_rules ;;
    test)    test_rules ;;
    *)       echo "Unknown mode: $MODE"; exit 1 ;;
esac
