#!/bin/bash
#
# ima_policy_gen.sh - IMA Policy Generator
#
#
# Generates an IMA (Integrity Measurement Architecture) policy based on
# analysis of the current system. The generated policy measures and
# optionally appraises executables, libraries, kernel modules, and
# firmware files.
#
# Usage: sudo ./ima_policy_gen.sh [--measure-only|--appraise|--audit]
#                                 [--output FILE] [--strict]
#
# Modes:
#   --measure-only  Generate measurement rules only (default)
#   --appraise      Generate appraisal rules (blocks unauthorized files)
#   --audit         Generate audit rules (logs but does not block)
#   --strict        Include additional strict rules
#   --output FILE   Write policy to FILE (default: stdout)
#

set -euo pipefail

# ── Configuration ───────────────────────────────────────────────

MODE="measure"
OUTPUT=""
STRICT=0
PCR_NUM=10

# ── Parse arguments ─────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --measure-only) MODE="measure"; shift ;;
        --appraise)     MODE="appraise"; shift ;;
        --audit)        MODE="audit"; shift ;;
        --strict)       STRICT=1; shift ;;
        --output)       OUTPUT="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: $0 [--measure-only|--appraise|--audit] [--output FILE] [--strict]"
            echo ""
            echo "Generates IMA policy rules based on system analysis."
            echo ""
            echo "Options:"
            echo "  --measure-only  Measurement rules only (default, non-blocking)"
            echo "  --appraise      Appraisal rules (blocks files that fail verification)"
            echo "  --audit         Audit rules (logs to audit subsystem)"
            echo "  --strict        Include additional strict rules"
            echo "  --output FILE   Write policy to FILE instead of stdout"
            echo ""
            echo "Must be run as root."
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [[ $(id -u) -ne 0 ]]; then
    echo "WARNING: Not running as root. Some system analysis may be incomplete." >&2
fi

# ── Helper functions ────────────────────────────────────────────

emit() {
    if [[ -n "$OUTPUT" ]]; then
        echo "$1" >> "$OUTPUT"
    else
        echo "$1"
    fi
}

emit_comment() {
    emit "# $1"
}

# ── Discover filesystem magic numbers ───────────────────────────

# Virtual filesystems that should be excluded from IMA
declare -A VIRTUAL_FS_MAGIC=(
    ["proc"]="0x9fa0"
    ["sysfs"]="0x62656572"
    ["debugfs"]="0x64626720"
    ["tmpfs"]="0x1021994"
    ["ramfs"]="0x858458f6"
    ["securityfs"]="0x73636673"
    ["devpts"]="0x1cd1"
    ["cgroup2"]="0x63677270"
    ["bpf"]="0xcafe4a11"
    ["tracefs"]="0x74726163"
    ["hugetlbfs"]="0x958458f6"
    ["mqueue"]="0x19800202"
    ["binfmt_misc"]="0x42494e4d"
    ["pstore"]="0x6165676c"
    ["efivarfs"]="0xde5e81e4"
    ["nsfs"]="0x6e736673"
    ["configfs"]="0x62656570"
)

# ── Discover active mount types ─────────────────────────────────

echo "Analyzing system mount points..." >&2

ACTIVE_FS_TYPES=$(mount | awk '{print $5}' | sort -u)

# ── Begin policy generation ─────────────────────────────────────

if [[ -n "$OUTPUT" ]]; then
    > "$OUTPUT"  # Truncate output file
    echo "Generating IMA policy to: $OUTPUT" >&2
fi

emit_comment "============================================================"
emit_comment " IMA Policy - Auto-generated by ima_policy_gen.sh"
emit_comment " Date: $(date)"
emit_comment " Hostname: $(hostname)"
emit_comment " Kernel: $(uname -r)"
emit_comment " Mode: $MODE"
emit_comment " Strict: $STRICT"
emit_comment "============================================================"
emit ""

# ── Section 1: Virtual filesystem exclusions ────────────────────

emit_comment "--- Section 1: Exclude Virtual Filesystems ---"
emit_comment "These filesystems generate content dynamically;"
emit_comment "measuring/appraising them is meaningless and causes issues."
emit ""

for fs_name in "${!VIRTUAL_FS_MAGIC[@]}"; do
    magic="${VIRTUAL_FS_MAGIC[$fs_name]}"
    emit "dont_measure fsmagic=$magic"
    if [[ "$MODE" == "appraise" ]]; then
        emit "dont_appraise fsmagic=$magic"
    fi
done
emit ""

# ── Section 2: Executable measurement/appraisal ────────────────

emit_comment "--- Section 2: Executable Binary Protection ---"
emit_comment "Measure/appraise all executables loaded via exec()."
emit ""

emit "measure func=BPRM_CHECK pcr=$PCR_NUM"
if [[ "$MODE" == "appraise" ]]; then
    emit "appraise func=BPRM_CHECK"
fi
if [[ "$MODE" == "audit" ]]; then
    emit "audit func=BPRM_CHECK"
fi
emit ""

# ── Section 3: Shared library protection ────────────────────────

emit_comment "--- Section 3: Shared Library Protection ---"
emit_comment "Measure/appraise all files loaded via mmap with PROT_EXEC."
emit ""

emit "measure func=FILE_MMAP mask=MAY_EXEC pcr=$PCR_NUM"
if [[ "$MODE" == "appraise" ]]; then
    emit "appraise func=FILE_MMAP mask=MAY_EXEC"
fi
if [[ "$MODE" == "audit" ]]; then
    emit "audit func=FILE_MMAP mask=MAY_EXEC"
fi
emit ""

# ── Section 4: Kernel module protection ─────────────────────────

emit_comment "--- Section 4: Kernel Module Protection ---"
emit_comment "Measure and optionally require signatures for kernel modules."
emit ""

emit "measure func=MODULE_CHECK pcr=$PCR_NUM"
if [[ "$MODE" == "appraise" ]]; then
    emit "appraise func=MODULE_CHECK appraise_type=imasig"
fi
if [[ "$MODE" == "audit" ]]; then
    emit "audit func=MODULE_CHECK"
fi
emit ""

# ── Section 5: Firmware protection ──────────────────────────────

emit_comment "--- Section 5: Firmware Protection ---"
emit_comment "Measure/appraise firmware loaded by the kernel."
emit ""

emit "measure func=FIRMWARE_CHECK pcr=$PCR_NUM"
if [[ "$MODE" == "appraise" ]]; then
    emit "appraise func=FIRMWARE_CHECK"
fi
emit ""

# ── Section 6: Kexec protection ─────────────────────────────────

emit_comment "--- Section 6: Kexec Protection ---"
emit_comment "Measure/appraise kernels loaded via kexec."
emit ""

emit "measure func=KEXEC_KERNEL_CHECK pcr=$PCR_NUM"
emit "measure func=KEXEC_INITRAMFS_CHECK pcr=$PCR_NUM"
if [[ "$MODE" == "appraise" ]]; then
    emit "appraise func=KEXEC_KERNEL_CHECK appraise_type=imasig"
    emit "appraise func=KEXEC_INITRAMFS_CHECK appraise_type=imasig"
fi
emit ""

# ── Section 7: Policy self-protection ───────────────────────────

emit_comment "--- Section 7: IMA Policy Self-Protection ---"
emit_comment "Measure and require signatures for IMA policy updates."
emit ""

emit "measure func=POLICY_CHECK pcr=$PCR_NUM"
if [[ "$MODE" == "appraise" ]]; then
    emit "appraise func=POLICY_CHECK appraise_type=imasig"
fi
emit ""

# ── Section 8: Strict mode additions ───────────────────────────

if [[ $STRICT -eq 1 ]]; then
    emit_comment "--- Section 8: Strict Mode Rules ---"
    emit_comment "Additional rules for high-security environments."
    emit ""

    # Measure all files read by root
    emit_comment "Audit all file reads by root (uid 0)"
    emit "audit func=FILE_CHECK mask=MAY_READ uid=0"
    emit ""

    # Measure key management operations
    emit_comment "Measure key operations"
    emit "measure func=KEY_CHECK pcr=$PCR_NUM"
    emit ""

    # Measure all files in /etc
    emit_comment "Measure configuration files in /etc"
    emit "measure func=FILE_CHECK mask=MAY_READ fowner=0 pcr=$PCR_NUM"
    emit ""
fi

# ── Section 9: Kexec command line ───────────────────────────────

emit_comment "--- Section 9: Boot Command Line ---"
emit_comment "Measure the kernel command line passed via kexec."
emit ""
emit "measure func=KEXEC_CMDLINE pcr=$PCR_NUM"
emit ""

# ── Summary ─────────────────────────────────────────────────────

emit_comment "============================================================"
emit_comment " End of IMA Policy"
emit_comment " "
emit_comment " To load this policy:"
emit_comment "   cat <policy_file> > /sys/kernel/security/ima/policy"
emit_comment " "
emit_comment " Or specify via kernel command line:"
emit_comment "   ima_policy=tcb  (for built-in TCB policy)"
emit_comment " "
emit_comment " For appraisal mode, first run in fix mode:"
emit_comment "   ima_appraise=fix (kernel parameter)"
emit_comment " Then sign files and switch to enforce mode:"
emit_comment "   ima_appraise=enforce"
emit_comment "============================================================"

# ── Print summary to stderr ─────────────────────────────────────

echo "" >&2
echo "=== IMA Policy Generation Complete ===" >&2
echo "  Mode: $MODE" >&2
echo "  Strict: $([ $STRICT -eq 1 ] && echo 'YES' || echo 'NO')" >&2
echo "  PCR: $PCR_NUM" >&2
echo "  Virtual FS exclusions: ${#VIRTUAL_FS_MAGIC[@]}" >&2
if [[ -n "$OUTPUT" ]]; then
    RULE_COUNT=$(grep -c '^[a-z]' "$OUTPUT" 2>/dev/null || echo "0")
    echo "  Rules generated: $RULE_COUNT" >&2
    echo "  Output: $OUTPUT" >&2
fi
echo "" >&2
echo "Next steps:" >&2
echo "  1. Review the generated policy" >&2
echo "  2. Test in measurement-only mode first" >&2
echo "  3. Gradually enable appraisal after signing files" >&2
echo "  4. Monitor IMA log: cat /sys/kernel/security/ima/ascii_runtime_measurements" >&2
